//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_Banque
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mouvement
    {
        public int Num_Mouvement { get; set; }
        public Nullable<int> Num_Compte { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public string TypeM { get; set; }
        public Nullable<System.DateTime> DateM { get; set; }
    
        public virtual Compte Compte { get; set; }
    }
}
