//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_Banque
{
    using System;
    using System.Collections.Generic;
    
    public partial class Virement
    {
        public int Num_Virement { get; set; }
        public Nullable<int> Num_Debiteur { get; set; }
        public Nullable<int> Num_Crediteur { get; set; }
        public Nullable<decimal> Montant_Vr { get; set; }
        public Nullable<System.DateTime> Date_Vr { get; set; }
    
        public virtual Compte Compte { get; set; }
        public virtual Compte Compte1 { get; set; }
    }
}
